### ISSUE TITLE
undefined method `strip' for nil:NilClass in 'ember_app_name' during rake db:schema:ember[:create]

### ISSUE THREAD

**Issue by BrennerSpear** [straydogstudio/ember_serialize#1]
My ember app, `frontend` is in my rails app directory. 
# config/initializers/ember_serialize.rb

`EmberSerialize::Serializer.javascripts_dir = "frontend/"`
`EmberSerialize::Serializer.app_name = "frontend/"`

I'm getting:
`undefined method `strip' for nil:NilClass`
`ember_serialize-0.0.9/lib/ember_serialize.rb:97:in `ember_app_name'`

Using:
Ruby 2.2.2
Rails 4.2.3
ember 1.13.8
active_model_serializers 0.8.3 (8d31f7e)
ember-cli-rails 0.3.5

**Comment by straydogstudio** [comment]
If you have used the standard `ember new`, your app_name should be 'App'. Give that a try and see if it fixes the error. 

I'm flying blind, not able to check anything where I am. I will try this gem out on ember-cli when I can.

**Comment by BrennerSpear** [comment]
tried commenting the app_name initializer line out, then tried:
`EmberSerialize::Serializer.app_name = "App"`

both gave the same error

**Comment by straydogstudio** [comment]
Locate your ember_serialize gem, and in [lib/ember_serialize.rb after line 87](https://github.com/straydogstudio/ember_serialize/blob/master/lib/ember_serialize.rb#L87), add

```
return 'App'
# before this line
@app_name ||= begin
```

I'm not sure why, but the settings in the initializer aren't being stored, and the code is trying to find the app name using the old syntax.

**Comment by straydogstudio** [comment]
If you use bundler `bundle show ember_serializer` should give you the location

**Comment by BrennerSpear** [comment]
Now I'm getting:

`NameError: uninitialized constant EmberSerialize::Serializer::App`

**Comment by straydogstudio** [comment]
Did you return a string 'App' or a constant App? Otherwise I will probably have to dig in and take a look at this.

**Comment by BrennerSpear** [comment]
Ah - my mistake.

now i'm getting a new error:
`NoMethodError: undefined method `klass' for nil:NilClass`

`activerecord-4.2.3/lib/active_record/reflection.rb:661:in `source_reflection'`
`activerecord-4.2.3/lib/active_record/reflection.rb:871:in `derive_class_name'`
`activerecord-4.2.3/lib/active_record/reflection.rb:147:in `class_name'`
`activerecord-4.2.3/lib/active_record/reflection.rb:640:in `klass'`
`activerecord-4.2.3/lib/active_record/reflection.rb:125:in `table_name'`
`ember_serialize-0.0.9/lib/ember_serialize.rb:138:in `ember_reflect'`
`ember_serialize-0.0.9/lib/ember_serialize.rb:232:in `block in ember_model_build'`
`ember_serialize-0.0.9/lib/ember_serialize.rb:229:in `each'`
`ember_serialize-0.0.9/lib/ember_serialize.rb:229:in `ember_model_build'`
`ember_serialize-0.0.9/lib/ember_serialize.rb:72:in `block in serialize'`
`ember_serialize-0.0.9/lib/ember_serialize.rb:64:in `each'`
`ember_serialize-0.0.9/lib/ember_serialize.rb:64:in `serialize'`
`ember_serialize-0.0.9/lib/tasks/ember_serialize_tasks.rake:5:in `block (3 levels) in <top (required)>'`

**Comment by straydogstudio** [comment]
It looks like there may be an issue with your assocation definition. Also, it could be ember_serialize. I assume your assocations are working ok, meaning asking for the has_many associations works ok? My logic may need to be updated for 4.2.

The failure is here:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/reflection.rb#L648-L667

**Comment by BrennerSpear** [comment]
I have `has_many :orders,  through: :shops, source: :order`
When I change it to:
`has_many :order,  through: :shops, source: :order`
it works.

It generates a frontend/models/brand.js.coffee file
(not a frontend/app/models/brand.js.coffee file - I don't really know/understand the difference)

in brand.js.coffee, it has this relation:
`shop: DS.belongsTo('shop', {async: true})`
I thought the `shop` was suppose to belongsTo the `brand`?
This seems the other way around?
Also, there are no `has_many` associations in the file - I would think there would have been one generated?

The next error I run into is `NameError: uninitialized constant FollowedBy::Followable`

`Followable` is a polymorphic name for `Brand` or  `Shopper`. The `FolllowedBy` table is a joint table between `Followers` and a `Followable` model. Maybe ember_serialize doesn't support polymorphic?

**Comment by straydogstudio** [comment]
Yep. Shop belongs to shop is a bit off. That should be a has many. 

I'm guessing this isn't yet usable with Rails 4.2, and definitely isn't with ember-cli. I will try to get to this soon. You're the first person to contact me about the gem, so I didn't have any indication anyone was using it. I let it slide. Doh!

It needs a few things:
- Testing with Rails 4.2
- ember-cli support
- output ES6 javascript, not coffeescript or emberscript (which are no longer in favor)

I'll release a new version and let you know on this thread. I am covering three jobs and I am moving, so I can't promise how soon this will happen. But I am committed to it so it will. 

I also may see if I can implement it with jsonapi-resources, which is the direction I am leaning now for creating an api. You might take a look at it; Sean Devine of the Ruby on Rails podcast speaks highly of it.

**Comment by BrennerSpear** [comment]
It took me a bit of searching to find your gem, but I would think Rails->Ember is fairly popular now, so I'm surprised more people aren't trying to keep their models in sync systematically.

I will generate them manually for now and hope I can do it right.

Everywhere I've read about Rails+Ember apps has mentioned AMS, but I haven't seen jsonapi-resources. I'll take a look at it

**Comment by straydogstudio** [comment]
You might be interested in this online training:
https://www.picatic.com/api-first-training-2015-09

Use the emberweekly promo code for $800. Probably well worth the money. I'm hoping to "attend".
